### ISSUE TITLE
ios fuse preview app throws errors

### ISSUE THREAD

**Issue by gianniskarmas** [fuse-open/fuse-studio#13]
It just doesn't work anymore.
If it is not a totally blank project I keep getting errors like:
`Fuse.Reactive.Each.SourceLineNumber' has no setter`
Any solutions available?

**Comment by lorents** [comment]
If you're on a mac (with XCode installed) you could try deploying a custom preview app from the menu under Preview -> Preview on iOS and see if the problem persists

**Comment by AL-Mutasim** [comment]
i have the same error in ios preview app and android as well

**Comment by BeeWarloc** [comment]
Unfortunately updating the Fuse Preview app was forgotten during the release of `1.9.0`, in the midst of all the changes.

I had a plan to get that done today and also get the process documented. _However_, there is an error preventing me from doing so, due to some changes before the open sourcing.

Specifically, running the script [Source/Preview/App/build.sh](https://github.com/fuse-open/fuse-studio/blob/1.9.0/Source/Preview/App/build.sh) now gives me this error:

```
Compiling syntax tree
Fuse.Simulator/SimulatorClient.uno(149.36): E3102: There is nothing named 'BinaryMessageInbox' accessible in this scope. Are you missing a package reference?
1.72 s
```

**Comment by lorents** [comment]
It should be safe to remove the `_alsoReceieveMessagesFromPipe` variable and all the references to it, including [the line](https://github.com/fuse-open/fuse-studio/blob/master/Source/Preview/App/Fuse.Simulator/SimulatorClient.uno#L149) causing this error.

(For reference, this class appears to have been copied from https://github.com/fuse-open/fuse-studio/blob/master/Source/Preview/Core/SimulatorClient.uno where this has since been removed)

**Comment by ianychoi** [comment]
@BeeWarloc I make a pull request by testing @lorents 's suggestion - both Android & iOS app built locally worked well. Would you kindly review & approve my pull request, and then release a new Preview apps on App Store and Play Store?

**Comment by BeeWarloc** [comment]
Sorry about the delay, an updated version of the preview app compatible with 1.9.0 should now be available on both the Android and iOS app stores.

I have tested that the Android release works, but unfortunately I don't have an iOS device at hand. So I'd appreciate feedback on whether the iOS version actually works or not.

**Comment by gianniskarmas** [comment]
It works, thank you
